import uuid
from django.db import models
from django.conf import settings

class Message(models.Model):
    # UUID generated by the PHONE. 
    # Server checks this to ensure we don't save the same message twice.
    client_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True)
    
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="sent_messages",
        on_delete=models.CASCADE,
    )
    receiver = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="received_messages",
        on_delete=models.CASCADE,
    )

    status = models.CharField(
        max_length=20, 
        default='sent',
        choices=[
            ('sent', 'Sent'), 
            ('delivered', 'Delivered'), 
            ('read', 'Read')
        ]
    )
    
    # We rename 'content' to 'encrypted_content' to be clear: The server CANNOT read this.
    encrypted_content = models.TextField(blank=True) 
    attachment = models.ImageField(upload_to="chat/", blank=True, null=True)
    
    # Timestamp is used for sorting in the sync queue
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']
        indexes = [
            # "Show me all messages between Me and Sam"
            models.Index(fields=['sender', 'receiver']),
            # "Show me messages for Me that came after ID 500" Sync instant.
            models.Index(fields=['receiver', 'id']),
        ]

    def __str__(self):
        return f"{self.sender} -> {self.receiver} [{self.client_id}]"