# Generated by Django 6.0.1 on 2026-01-14 08:20

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_online_user_blocking'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),

        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='accounts_co_sender__1feb14_idx',
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='accounts_co_status_2f0a8c_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
