# Generated by Django 6.0.1 on 2026-01-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pushtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushtoken',
            options={'verbose_name': 'Push Token', 'verbose_name_plural': 'Push Tokens'},
        ),
        migrations.RenameField(
            model_name='pushtoken',
            old_name='updated_at',
            new_name='last_used_at',
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
