# Generated by Django 6.0.1 on 2026-01-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pushtoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('token', models.CharField(max_length=1024)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='pushtoken',
            name='accounts_pu_user_id_261b88_idx',
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pushtoken',
            name='user',
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['user', 'last_seen_at'], name='accounts_pu_user_id_10566d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pushdevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.DeleteModel(
            name='PushToken',
        ),
    ]
