# Generated by Django 6.0.1 on 2026-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pushdevice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pushdevice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pushdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_device'),
        ),
    ]
