# Generated by Django 6.0.1 on 2026-01-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_device_userdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='hardware_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['token'], name='accounts_us_token_0a6822_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('platform', 'hardware_id'), name='unique_physical_device'),
        ),
    ]
