# Generated by Django 6.0.1 on 2026-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content_comment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processing',
            field=models.BooleanField(default=True),
        ),
    ]
