# Generated by Django 6.0.1 on 2026-01-16 10:11

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_timesta_6494d7_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='encrypted_content',
        ),
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_id'], name='chat_messag_client__7a1de3_idx'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
