# Generated by Django 6.0.1 on 2026-01-17 20:39

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_chat_messag_timesta_6494d7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_client__7a1de3_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'id'], name='chat_messag_receive_878a87_idx'),
        ),
    ]
