# Generated by Django 6.0.1 on 2026-01-18 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_receive_878a87_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'timestamp'], name='chat_messag_receive_e6f8c8_idx'),
        ),
    ]
