# Generated by Django 6.0.1 on 2026-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_chat_messag_receive_878a87_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
