# Generated by Django 6.0.1 on 2026-01-26 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_options_remove_message_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_globally',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('deleted', 'Deleted')], default='sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_id'], name='chat_messag_client__7a1de3_idx'),
        ),
    ]
