# Generated by Django 6.0.1 on 2026-01-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_deleted_for_message_deleted_globally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
